.PHONY: clean All

All:
	@echo "----------Building project:[ PrimeNumberFunction - Debug ]----------"
	@cd "PrimeNumberFunction" && "$(MAKE)" -f  "PrimeNumberFunction.mk"
clean:
	@echo "----------Cleaning project:[ PrimeNumberFunction - Debug ]----------"
	@cd "PrimeNumberFunction" && "$(MAKE)" -f  "PrimeNumberFunction.mk" clean
