.PHONY: clean All

All:
	@echo "----------Building project:[ valeraAndX - Debug ]----------"
	@cd "valeraAndX" && "$(MAKE)" -f  "valeraAndX.mk"
clean:
	@echo "----------Cleaning project:[ valeraAndX - Debug ]----------"
	@cd "valeraAndX" && "$(MAKE)" -f  "valeraAndX.mk" clean
