.PHONY: clean All

All:
	@echo "----------Building project:[ createClass - Debug ]----------"
	@cd "createClass" && "$(MAKE)" -f  "createClass.mk"
clean:
	@echo "----------Cleaning project:[ createClass - Debug ]----------"
	@cd "createClass" && "$(MAKE)" -f  "createClass.mk" clean
