.PHONY: clean All

All:
	@echo "----------Building project:[ kkk - Debug ]----------"
	@cd "kkk" && "$(MAKE)" -f  "kkk.mk"
clean:
	@echo "----------Cleaning project:[ kkk - Debug ]----------"
	@cd "kkk" && "$(MAKE)" -f  "kkk.mk" clean
