.PHONY: clean All

All:
	@echo "----------Building project:[ team - Debug ]----------"
	@cd "team" && "$(MAKE)" -f  "team.mk"
clean:
	@echo "----------Cleaning project:[ team - Debug ]----------"
	@cd "team" && "$(MAKE)" -f  "team.mk" clean
