.PHONY: clean All

All:
	@echo "----------Building project:[ investfuture - Debug ]----------"
	@cd "investfuture" && "$(MAKE)" -f  "investfuture.mk"
clean:
	@echo "----------Cleaning project:[ investfuture - Debug ]----------"
	@cd "investfuture" && "$(MAKE)" -f  "investfuture.mk" clean
