.PHONY: clean All

All:
	@echo "----------Building project:[ MarlinAndAddress - Debug ]----------"
	@cd "MarlinAndAddress" && "$(MAKE)" -f  "MarlinAndAddress.mk"
clean:
	@echo "----------Cleaning project:[ MarlinAndAddress - Debug ]----------"
	@cd "MarlinAndAddress" && "$(MAKE)" -f  "MarlinAndAddress.mk" clean
