.PHONY: clean All

All:
	@echo "----------Building project:[ student - Debug ]----------"
	@cd "student" && "$(MAKE)" -f  "student.mk"
clean:
	@echo "----------Cleaning project:[ student - Debug ]----------"
	@cd "student" && "$(MAKE)" -f  "student.mk" clean
